name: build and package docker image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: external workflow
    uses: tehw0lf/workflows/.github/workflows/build-test-publish.yml@main
    permissions:
      actions: write
      contents: write
      packages: write
    with:
      tool: 'npm'
      format: 'run format'
      install: 'install --legacy-peer-deps'
      lint: 'run lint'
      test: 'run test --ci --code-coverage'
      build_branch: 'run build'
      build_main: 'run build --skip-nx-cache'
      event_name: ${{ github.event_name }}
      docker_meta: '[{"name":"states","file":"Dockerfile"}]'
      artifact_path: 'dist/states/browser/'
